class LiquidsoapConfigService
  CONFIG_PATH = Rails.root.join("storage", "liquidsoap", "radio.liq")

  def self.call
    new.call
  end

  def call
    stations = RadioStation.where.not(status: "stopped").includes(:playlist)
    config = generate(stations)
    write(config)
    config
  end

  private

  def generate(stations)
    parts = []
    parts << "# Generated by synthwaves.fm"
    parts << "# Generated at: #{Time.current.iso8601}"
    parts << ""
    parts << settings_block
    parts << ""
    stations.each { |s| parts << station_block(s) }
    parts.join("\n")
  end

  def settings_block
    <<~LIQ.chomp
      log.level.set(3)
      settings.http.normalize_url.set(false)

      rails_host = environment.get(default="localhost:3000", "RAILS_HOST")
      rails_protocol = environment.get(default="http", "RAILS_PROTOCOL")
      auth_token = environment.get(default="", "LIQUIDSOAP_API_TOKEN")
      icecast_host = environment.get(default="localhost", "ICECAST_INTERNAL_HOST")
      icecast_port = int_of_string(environment.get(default="8000", "ICECAST_INTERNAL_PORT"))
      icecast_password = environment.get(default="hackme", "ICECAST_SOURCE_PASSWORD")
    LIQ
  end

  def station_block(station)
    id = station.id
    slug = station.mount_point.delete_prefix("/").delete_suffix(".mp3")
    safe_id = slug.tr("-", "_")

    <<~LIQ.chomp
      # Station #{id}: #{station.playlist.name}
      def next_track_#{safe_id}() =
        url = rails_protocol ^ "://" ^ rails_host ^ "/api/internal/radio_stations/#{id}/next_track"
        body = http.get(headers=[("Authorization", "Bearer " ^ auth_token)], url)
        if body == "" then
          null()
        else
          let json.parse (data : {url: string}) = body
          if data.url == "" then
            null()
          else
            request.create(data.url)
          end
        end
      end

      station_#{safe_id} = request.dynamic(id="#{slug}", next_track_#{safe_id})
      #{crossfade_line(station, safe_id)}

      station_#{safe_id} = mksafe(station_#{safe_id})

      output.icecast(
        %mp3(bitrate=#{station.bitrate}),
        host=icecast_host,
        port=icecast_port,
        password=icecast_password,
        mount="#{station.mount_point}",
        name=#{liquidsoap_string(station.playlist.name)},
        station_#{safe_id}
      )
    LIQ
  end

  def crossfade_line(station, safe_id)
    if station.crossfade
      "station_#{safe_id} = crossfade(duration=#{station.crossfade_duration}, station_#{safe_id})"
    else
      ""
    end
  end

  def liquidsoap_string(str)
    "\"#{str.gsub("\\", "\\\\\\\\").gsub('"', '\\"')}\""
  end

  def write(config)
    dir = CONFIG_PATH.dirname
    FileUtils.mkdir_p(dir)
    File.write(CONFIG_PATH, config)
  end
end
