use domain::models::RadioStation;

pub fn generate_config(
    stations: &[RadioStation],
    rails_host: &str,
    rails_protocol: &str,
) -> String {
    let mut out = vec![
        "# Generated by synthwaves.fm (Rust)".to_string(),
        "log.level.set(3)".to_string(),
        "settings.http.normalize_url.set(false)".to_string(),
        "auth_token = environment.get(default=\"\", \"LIQUIDSOAP_API_TOKEN\")".to_string(),
        "icecast_host = environment.get(default=\"localhost\", \"ICECAST_INTERNAL_HOST\")"
            .to_string(),
        "icecast_port = int_of_string(environment.get(default=\"8000\", \"ICECAST_INTERNAL_PORT\"))"
            .to_string(),
        "icecast_password = environment.get(default=\"hackme\", \"ICECAST_SOURCE_PASSWORD\")"
            .to_string(),
        String::new(),
    ];

    for station in stations {
        let slug = station
            .mount_point
            .trim_start_matches('/')
            .trim_end_matches(".mp3")
            .replace('-', "_");
        out.push(format!(
            "# Station {}: {}",
            station.id, station.playlist_name
        ));
        out.push(format!("def next_track_{slug}() ="));
        out.push(format!(
            "  url = \"{rails_protocol}://{rails_host}/api/internal/radio_stations/{}/next_track\"",
            station.id
        ));
        out.push(
            "  body = http.get(headers=[(\"Authorization\", \"Bearer \" ^ auth_token)], url)"
                .to_string(),
        );
        out.push("  if body == \"\" then null() else".to_string());
        out.push("    let json.parse (data : {url: string}) = body".to_string());
        out.push(
            "    if data.url == \"\" then null() else request.create(data.url) end".to_string(),
        );
        out.push("  end".to_string());
        out.push("end".to_string());
        out.push(format!(
            "station_{slug} = request.dynamic(id=\"{slug}\", next_track_{slug})"
        ));
        if station.crossfade {
            out.push(format!(
                "station_{slug} = crossfade(duration={}, station_{slug})",
                station.crossfade_duration
            ));
        }
        out.push(format!("station_{slug} = mksafe(station_{slug})"));
        out.push(format!(
            "output.icecast(%mp3(bitrate={}), host=icecast_host, port=icecast_port, password=icecast_password, mount=\"{}\", name=\"{}\", station_{slug})",
            station.bitrate, station.mount_point, station.playlist_name
        ));
        out.push(String::new());
    }
    out.join("\n")
}
