# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  cleanup_expired_downloads:
    command: "Download.expired.find_each { |d| d.file.purge if d.file.attached?; d.destroy }"
    schedule: every hour at minute 30
  cleanup_stale_downloads:
    command: "Download.stale.update_all(status: 'failed', error_message: 'Timed out')"
    schedule: every hour at minute 45
  # iptv_channel_sync:
  #   class: IPTVChannelSyncJob
  #   schedule: at 4am every day
  epg_sync:
    class: EPGSyncJob
    schedule: every 3 hours
  database_backup:
    class: DatabaseBackupJob
    schedule: at 3am every day
