require "rails_helper"

RSpec.describe LiquidsoapConfigService do
  let(:user) { create(:user) }

  describe ".call" do
    it "generates an empty config when no active stations" do
      config = LiquidsoapConfigService.call

      expect(config).to include("Generated by synthwaves.fm")
      expect(config).not_to include("output.icecast")
    end

    it "generates config for active stations" do
      playlist = create(:playlist, name: "Chill Vibes", user: user)
      create(:radio_station,
        playlist: playlist,
        user: user,
        status: "active",
        mount_point: "/chill-vibes.mp3",
        bitrate: 192,
        crossfade: true,
        crossfade_duration: 3.0)

      config = LiquidsoapConfigService.call

      expect(config).to include("output.icecast")
      expect(config).to include("/chill-vibes.mp3")
      expect(config).to include("bitrate=192")
      expect(config).to include("crossfade(duration=3.0")
      expect(config).to include("Chill Vibes")
      expect(config).not_to include("on_metadata")
    end

    it "excludes stopped stations" do
      playlist = create(:playlist, name: "Stopped Station", user: user)
      create(:radio_station, playlist: playlist, user: user, status: "stopped", mount_point: "/stopped.mp3")

      config = LiquidsoapConfigService.call
      expect(config).not_to include("/stopped.mp3")
    end

    it "omits crossfade when disabled" do
      playlist = create(:playlist, name: "No Fade", user: user)
      create(:radio_station,
        playlist: playlist,
        user: user,
        status: "active",
        mount_point: "/no-fade.mp3",
        crossfade: false)

      config = LiquidsoapConfigService.call
      expect(config).not_to include("crossfade(duration=")
    end

    it "writes the config file to disk" do
      config_path = LiquidsoapConfigService::CONFIG_PATH

      LiquidsoapConfigService.call

      expect(File.exist?(config_path)).to be true
      expect(File.read(config_path)).to include("Generated by synthwaves.fm")
    ensure
      FileUtils.rm_f(config_path)
    end
  end
end
